### ISSUE TITLE
2.7inch e-Paper e-Ink Display HAT (B) For Raspberry Pi, 264×176, "Red / Black / White, SPIÉis that there is the possibility to make it work with 2.7inch e-Paper e-Ink Display HAT (B) For Raspberry Pi, 264×176, Red / Black / White, SPI"

### ISSUE THREAD

**Issue by dish67** [llvllch/btcticker#62]
Hi

Is that there is the possibility to make it work with 2.7inch e-Paper e-Ink Display HAT (B) For Raspberry Pi, 264×176, Red / Black / White, SPI

I change parameter  on btcticker.py

from waveshare_epd import epd2in7
**to** 
from waveshare_epd import epd2in7b_V2

and I change that ...

    epd = epd2in7b_V2.EPD()
#epd = epd2in7()
    epd.init()
#epd.Init_4Gray()
#epd.display_4Gray(epd.getbuffer_4Gray(img))
#epd.display(epd.getbuffer(img))

But I did't see any image on my e-paper ... 

do you have any suggestion ??

**Comment by llvllch** [comment]
Uncomment the line: 
#epd.display(epd.getbuffer(img))
?

**Comment by dish67** [comment]
Thank .. 
But I have this error !!  TypeError: display() missing 1 required positional argument: 'imagered'   <==


when I Uncomment the line and reexecute  
def display_image(img):
    epd = epd2in7b_V2.EPD()    epd.init()    print("Clear...")#    epd.Init_4Gray()#    epd.display_4Gray(epd.getbuffer_4Gray(img))    epd.display(epd.getbuffer(img))    epd.sleep()    initkeys()    return



python3 btcticker.py ...Clear...DEBUG:root:HorizontalTraceback (most recent call last):  File "btcticker.py", line 360, in fullupdate    display_image(image)  File "btcticker.py", line 319, in display_image    epd.display(epd.getbuffer(img))TypeError: display() missing 1 required positional argument: 'imagered'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):  File "btcticker.py", line 454, in main    lastcoinfetch=fullupdate(config,lastcoinfetch)  File "btcticker.py", line 366, in fullupdate    display_image(image)  File "btcticker.py", line 319, in display_image    epd.display(epd.getbuffer(img))TypeError: display() missing 1 required positional argument: 'imagered'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):  File "btcticker.py", line 473, in <module>    main()  File "btcticker.py", line 463, in main    display_image(image)  File "btcticker.py", line 319, in display_image    epd.display(epd.getbuffer(img))TypeError: display() missing 1 required positional argument: 'imagered'   <==





Michel Thibault

***@***.***

385 de gascogne ,

J4B 8T2 , Boucherville 

Quebec , Canada 

    Le mercredi 23 juin 2021, 14 h 03 min 49 s HAE, VEEB ***@***.***> a écrit :  
 
 


Uncomment the line:
#epd.display(epd.getbuffer(img))
?

**Comment by llvllch** [comment]
This is where it looks like it's different 'image red' sounds like you might have a separate image that determines the red part of the image
